const fs = require("fs");
const path = require("path");

const SCRIPT_DIR = __dirname;
const PROJECT_ROOT = path.resolve(SCRIPT_DIR, "..", "..");
const WORKSPACE_ROOT = path.resolve(PROJECT_ROOT, "..");
const OUTPUT_FILE = path.join(
  PROJECT_ROOT,
  "BP",
  "scripts",
  "core",
  "render",
  "generated",
  "customItemTexturePaths.js",
);
const TECHNICAL_ITEM_TAG = "utilitycraft:ui_element";

function stripJsonComments(text) {
  let output = "";
  let inString = false;
  let inLineComment = false;
  let inBlockComment = false;
  let escaped = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (inLineComment) {
      if (char === "\n" || char === "\r") {
        inLineComment = false;
        output += char;
      }
      continue;
    }

    if (inBlockComment) {
      if (char === "*" && next === "/") {
        inBlockComment = false;
        index += 1;
      }
      continue;
    }

    if (inString) {
      output += char;
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === '"') inString = false;
      continue;
    }

    if (char === '"') {
      inString = true;
      output += char;
    } else if (char === "/" && next === "/") {
      inLineComment = true;
      index += 1;
    } else if (char === "/" && next === "*") {
      inBlockComment = true;
      index += 1;
    } else {
      output += char;
    }
  }

  return output;
}

function readJson(filePath) {
  try {
    return JSON.parse(stripJsonComments(fs.readFileSync(filePath, "utf8")));
  } catch {
    return undefined;
  }
}

function walkJsonFiles(directory, output = []) {
  if (!fs.existsSync(directory)) return output;

  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) walkJsonFiles(entryPath, output);
    else if (entry.isFile() && entry.name.endsWith(".json")) output.push(entryPath);
  }

  return output;
}

function resolvePackPath(projectPath, folder) {
  const direct = path.join(projectPath, folder);
  if (fs.existsSync(direct)) return direct;

  const nested = path.join(projectPath, "packs", folder);
  return fs.existsSync(nested) ? nested : undefined;
}

function getProjects() {
  return fs.readdirSync(WORKSPACE_ROOT, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const projectPath = path.join(WORKSPACE_ROOT, entry.name);
      return {
        name: entry.name,
        bp: resolvePackPath(projectPath, "BP"),
        rp: resolvePackPath(projectPath, "RP"),
      };
    })
    .filter((project) => project.bp && project.rp)
    .sort((left, right) => left.name.localeCompare(right.name));
}

function firstTexturePath(entry) {
  const textures = entry?.textures;
  const value = Array.isArray(textures) ? textures[0] : textures;
  if (typeof value === "string") return value;
  return typeof value?.path === "string" ? value.path : undefined;
}

function getIconKey(itemDefinition) {
  const icon = itemDefinition?.components?.["minecraft:icon"];
  if (typeof icon === "string") return icon;
  if (typeof icon?.textures?.default === "string") return icon.textures.default;
  if (typeof icon?.texture === "string") return icon.texture;
  return typeof icon?.textures === "string" ? icon.textures : undefined;
}

function isTechnicalItem(itemDefinition) {
  const tags = itemDefinition?.components?.["minecraft:tags"]?.tags;
  return Array.isArray(tags) && tags.includes(TECHNICAL_ITEM_TAG);
}

function collectTexturePaths() {
  const result = {};

  for (const project of getProjects()) {
    const atlas = readJson(path.join(project.rp, "textures", "item_texture.json"))?.texture_data ?? {};
    const itemFiles = walkJsonFiles(path.join(project.bp, "items"));

    for (const filePath of itemFiles) {
      const item = readJson(filePath)?.["minecraft:item"];
      const identifier = item?.description?.identifier;
      if (!identifier || identifier.startsWith("minecraft:") || isTechnicalItem(item)) continue;

      const iconKey = getIconKey(item);
      const texturePath = iconKey?.startsWith("textures/")
        ? iconKey
        : firstTexturePath(atlas[iconKey]);
      if (texturePath) result[identifier] = texturePath;
    }
  }

  return Object.fromEntries(Object.entries(result).sort(([left], [right]) => left.localeCompare(right)));
}

const customItemTexturePaths = collectTexturePaths();
fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(
  OUTPUT_FILE,
  `// Generated by scripts/tools/generateItemTexturePaths.js.\nexport const customItemTexturePaths = ${JSON.stringify(customItemTexturePaths, null, 2)};\n`,
);
console.log(`[item-textures] Generated ${Object.keys(customItemTexturePaths).length} custom item texture paths.`);
