// Generated from Mojang's vanilla behavior-pack entity definitions.
export const BREEDING_ITEMS_BY_ENTITY = Object.freeze({
  "minecraft:armadillo": ["minecraft:spider_eye"],
  "minecraft:axolotl": ["minecraft:tropical_fish_bucket"],
  "minecraft:bee": [
    "minecraft:poppy", "minecraft:blue_orchid", "minecraft:allium",
    "minecraft:azure_bluet", "minecraft:red_tulip", "minecraft:orange_tulip",
    "minecraft:white_tulip", "minecraft:pink_tulip", "minecraft:oxeye_daisy",
    "minecraft:cornflower", "minecraft:lily_of_the_valley", "minecraft:dandelion",
    "minecraft:wither_rose", "minecraft:sunflower", "minecraft:lilac",
    "minecraft:rose_bush", "minecraft:peony", "minecraft:flowering_azalea",
    "minecraft:azalea_leaves_flowered", "minecraft:mangrove_propagule",
    "minecraft:pitcher_plant", "minecraft:torchflower", "minecraft:cherry_leaves",
    "minecraft:pink_petals", "minecraft:wildflowers", "minecraft:cactus_flower",
    "minecraft:chorus_flower", "minecraft:spore_blossom",
  ],
  "minecraft:camel": ["minecraft:cactus"],
  "minecraft:cat": ["minecraft:cod", "minecraft:salmon"],
  "minecraft:chicken": [
    "minecraft:wheat_seeds", "minecraft:beetroot_seeds", "minecraft:melon_seeds",
    "minecraft:pumpkin_seeds", "minecraft:pitcher_pod", "minecraft:torchflower_seeds",
  ],
  "minecraft:cow": ["minecraft:wheat"],
  "minecraft:donkey": [
    "minecraft:golden_carrot", "minecraft:golden_apple",
    "minecraft:enchanted_golden_apple",
  ],
  "minecraft:fox": ["minecraft:sweet_berries", "minecraft:glow_berries"],
  "minecraft:frog": ["minecraft:slime_ball"],
  "minecraft:goat": ["minecraft:wheat"],
  "minecraft:hoglin": ["minecraft:crimson_fungus"],
  "minecraft:horse": [
    "minecraft:golden_carrot", "minecraft:golden_apple",
    "minecraft:enchanted_golden_apple",
  ],
  "minecraft:llama": ["minecraft:hay_block"],
  "minecraft:mooshroom": ["minecraft:wheat"],
  "minecraft:nautilus": [
    "minecraft:pufferfish_bucket", "minecraft:cod_bucket", "minecraft:salmon_bucket",
    "minecraft:tropical_fish_bucket", "minecraft:pufferfish", "minecraft:cod",
    "minecraft:salmon", "minecraft:tropical_fish", "minecraft:cooked_cod",
    "minecraft:cooked_salmon",
  ],
  "minecraft:ocelot": ["minecraft:cod", "minecraft:salmon"],
  "minecraft:panda": ["minecraft:bamboo"],
  "minecraft:pig": ["minecraft:carrot", "minecraft:beetroot", "minecraft:potato"],
  "minecraft:rabbit": ["minecraft:golden_carrot", "minecraft:carrot", "minecraft:dandelion"],
  "minecraft:sheep": ["minecraft:wheat"],
  "minecraft:sniffer": ["minecraft:torchflower_seeds"],
  "minecraft:strider": ["minecraft:warped_fungus"],
  "minecraft:trader_llama": ["minecraft:hay_block"],
  "minecraft:turtle": ["minecraft:seagrass"],
  "minecraft:wolf": [
    "minecraft:chicken", "minecraft:cooked_chicken", "minecraft:beef",
    "minecraft:cooked_beef", "minecraft:mutton", "minecraft:cooked_mutton",
    "minecraft:porkchop", "minecraft:cooked_porkchop", "minecraft:rabbit",
    "minecraft:cooked_rabbit", "minecraft:rotten_flesh",
  ],
});

export const KNOWN_TAMEABLE_ENTITY_IDS = new Set([
  "minecraft:cat",
  "minecraft:donkey",
  "minecraft:horse",
  "minecraft:llama",
  "minecraft:mule",
  "minecraft:nautilus",
  "minecraft:parrot",
  "minecraft:skeleton_horse",
  "minecraft:trader_llama",
  "minecraft:wolf",
  "minecraft:zombie_horse",
  "minecraft:zombie_nautilus",
]);

